apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack Fraud Alerts
    receivers:
      - uid: slack-fraud-alerts
        type: slack
        settings:
          recipient: "#all-fraud-detection-grafana-alerts"
          url: "${SLACK_WEBHOOK_URL}"
          title: '{{ template "slack.default.title" . }}'
          text: '{{ template "slack.default.text" . }}'
        disableResolveMessage: false