apiVersion: 1

datasources:
  - name: ClickHouse - Fraud Detection
    uid: afxn5yvy1qdj4f
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: fraud_detection
      username: fraud_user
    secureJsonData:
      password: change_me